//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastTunnel.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TunnelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TunnelResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastTunnel.Core.TunnelResource", typeof(TunnelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您尚未创建任何隧道，请登录https://suidao.io 创建后重试。 的本地化字符串。
        /// </summary>
        internal static string NoTunnel {
            get {
                return ResourceManager.GetString("NoTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page_HostRequired {
            get {
                return ResourceManager.GetString("Page_HostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page_NoSite {
            get {
                return ResourceManager.GetString("Page_NoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page_NotAccessIps {
            get {
                return ResourceManager.GetString("Page_NotAccessIps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Page_NoTunnel {
            get {
                return ResourceManager.GetString("Page_NoTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \n=====隧道已建立成功，现在可以通过以下方式访问您的内网服务了=====\n{0}\n 的本地化字符串。
        /// </summary>
        internal static string TunnelLlist {
            get {
                return ResourceManager.GetString("TunnelLlist", resourceCulture);
            }
        }
    }
}
