//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastTunnel.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TunnelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TunnelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastTunnel.Core.TunnelResource", typeof(TunnelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务端禁用了Forward.
        /// </summary>
        internal static string ForwardDisabled {
            get {
                return ResourceManager.GetString("ForwardDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尚未创建任何隧道，请登录https://suidao.io 创建后重试。.
        /// </summary>
        internal static string NoTunnel {
            get {
                return ResourceManager.GetString("NoTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page_HostRequired {
            get {
                return ResourceManager.GetString("Page_HostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page_NoSite {
            get {
                return ResourceManager.GetString("Page_NoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page_NotAccessIps {
            get {
                return ResourceManager.GetString("Page_NotAccessIps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;title&gt;FastTunnel&lt;/title&gt;
        ///  &lt;link href=&quot;https://cdn.bootcss.com/twitter-bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///  &lt;style&gt;
        ///    .err-info {
        ///      margin-top: 120px;
        ///    }
        ///
        ///    /* Provide sufficient contrast against white background */
        ///    a {
        ///      color: #0366d6;
        ///    }
        ///
        ///    .btn-primary {
        ///      color: #fff;
        ///      background-color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page_Offline {
            get {
                return ResourceManager.GetString("Page_NoTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 200 OK
        ///Date: Sat, 21 Aug 2021 15:14:17 GMT
        ///Content-Type: text/html; charset=utf-8
        ///Server: Microsoft-IIS/10.0
        ///X-Powered-By: ASP.NET
        ///Content-Length: 3026
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt; - BX.SignalR&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/lib/bootstrap/dist/css/bootstrap.min.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/css/site.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;head [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n=====隧道已建立成功，现在可以通过以下方式访问您的内网服务了=====\n{0}\n.
        /// </summary>
        internal static string TunnelLlist {
            get {
                return ResourceManager.GetString("TunnelLlist", resourceCulture);
            }
        }
    }
}
